function vonMises = vonMises_time(sigmaX,sigmaY,sigmaZ,tauXY,tauYZ,tauZX)
%VONMISES_TIME Calculate time-domain Von Mises stress
%
%https://web.mscsoftware.com/patran/current/html_patran/wwhelp/wwhimpl/js/html/wwhelp.htm#href=Results%20Postprocessing/res_numerics.15.4.html

    vonMises = sqrt(((sigmaX-sigmaY).^2 ...
                    +(sigmaY-sigmaZ).^2 ...
                    +(sigmaZ-sigmaX).^2)/2 ...
                 +3.*(tauXY.^2 ...
                     +tauYZ.^2 ...
                     +tauZX.^2));

end

